spring.application.name=backend-f
server.port=8882
logging.file.name=backend-f.log

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/familias}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect